"""update audit_log

Revision ID: a8925be7d930
Revises: b6e9096dd9c5
Create Date: 2026-03-27 00:41:44.786594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8925be7d930'
down_revision: Union[str, Sequence[str], None] = 'b6e9096dd9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
